---
- name: Install and configure Nginx on Linux servers
  hosts: {  host-name } ex- client
  become: yes

  tasks:

    - name: Install Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RHEL/CentOS
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
